// <auto-generated />
using System;
using CarsBD.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarsBD.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210903062015_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarsBD.EF.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BasePrice")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarsBD.EF.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Date")
                        .HasColumnType("int");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("car_id")
                        .HasColumnType("int");

                    b.Property<int?>("store_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("car_id");

                    b.HasIndex("store_id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("CarsBD.EF.ServiceCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("ServiceCenter");
                });

            modelBuilder.Entity("CarsBD.EF.ServiceJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("car_id")
                        .HasColumnType("int");

                    b.Property<int?>("centere_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("car_id");

                    b.HasIndex("centere_id");

                    b.ToTable("ServiceJobs");
                });

            modelBuilder.Entity("CarsBD.EF.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("CarsBD.EF.Sale", b =>
                {
                    b.HasOne("CarsBD.EF.Car", "Car")
                        .WithMany("Sales")
                        .HasForeignKey("car_id");

                    b.HasOne("CarsBD.EF.Store", "Store")
                        .WithMany("Sales")
                        .HasForeignKey("store_id");

                    b.Navigation("Car");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CarsBD.EF.ServiceJob", b =>
                {
                    b.HasOne("CarsBD.EF.Car", "Car")
                        .WithMany("ServiceJobs")
                        .HasForeignKey("car_id");

                    b.HasOne("CarsBD.EF.ServiceCenter", "ServiceCenter")
                        .WithMany("ServiceJobs")
                        .HasForeignKey("centere_id");

                    b.Navigation("Car");

                    b.Navigation("ServiceCenter");
                });

            modelBuilder.Entity("CarsBD.EF.Car", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("ServiceJobs");
                });

            modelBuilder.Entity("CarsBD.EF.ServiceCenter", b =>
                {
                    b.Navigation("ServiceJobs");
                });

            modelBuilder.Entity("CarsBD.EF.Store", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
